server:
  port: 9110

spring:
  datasource:
    url: "jdbc:h2:mem:store;MODE=MySQL;IGNORECASE=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;INIT=RUNSCRIPT FROM 'classpath:db/init_h2.sql';"
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: "none"
  zipkin:
    baseUrl: http://192.168.99.100:9411

uri:
  customizer:
    enabled: false
    
feign:
  hystrix:
    enabled: true
