server:
  port: 0

spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRES_PORT_5432_TCP_ADDR:192.168.99.100}:${POSTGRES_PORT_5432_TCP_PORT:5432}/${POSTGRES_DB:warehouse}"
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PASSWORD:sprio}"
  jpa:
    hibernate:
      ddl-auto: "none"

management:
  server:
    port: "1${server.port}"
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
  metrics:
    export:
      jmx:
        enabled: false
      graphite:
        enabled: false
